import fs from 'fs';
import path from 'path';
import {loadLogicalValidationSuite, TextTurn} from 'prix-fixe';

import {Converter} from '../for-python/converter';

///////////////////////////////////////////////////////////////////////////////
//
// Application to process a prix-fixe menu and test suite into files to be used
// in a Jupyter and Python data science environment. Produces
//
//   * out/menu.ts - Typescript interface definitions for the shopping cart
//                   data structure to be generated by LLMs. Can be included
//                   as grounding data in LLM prompt. Could also be converted
//                   to JSON schema.
//
//   * out/suite.json - test suite in a text-based format that doesn't require
//                      knowledge of  SKUs, PIDs, AIDs, or Keys.
//
//   * out/defaults.json - a map from product name to default configuration of
//                         the product. Used to supply default values so that
//                         the LLM doesn't have to fully specify an item.
//
///////////////////////////////////////////////////////////////////////////////

const dataPath = 'samples/menu';
const suitePath = 'samples/tests/baseline.yaml';
const outPath = 'output';

const friendlyAttributeNames = new Map<string, string>([
  ['coffee_temperature', 'temperature'],
  ['coffee_size', 'size'],
  ['espresso_size', 'size'],
  ['option_quantity', 'amount'],
  ['', ''],
]);

function go(dataPath: string, suitePath: string, outPath: string) {
  const converter = new Converter(dataPath, friendlyAttributeNames);

  const pfSuite = loadLogicalValidationSuite<TextTurn>(suitePath);

  write(
    outPath,
    'defaults.json',
    JSON.stringify(converter.createDefaults(), null, 2)
  );
  write(
    outPath,
    'suite.json',
    JSON.stringify(converter.convertTestSuite(pfSuite), null, 2)
  );
  write(outPath, 'menu.ts', converter.createTypeScriptMenu());
}

function write(outPath: string, name: string, data: string) {
  const filename = path.join(outPath, name);
  console.log(`Writing to ${filename}`);
  fs.writeFileSync(filename, data, 'utf-8');
}

go(dataPath, suitePath, outPath);
